### PR TITLE
Updates to OG-USA integration

### PR DESCRIPTION
**Pull request by jdebacker**
@andersonfrailey I made some modification to your branch that brings OG-USA into the model.

I've written some tests and confirmed with local runs that things are working as expected.

Left out:
1. Adding OG-USA to the `environment.yml` file.  There is not OG-USA conda package at the moment and installing from GitHub requires downloading the bloated test files.  I'm going to try to create a new OG-USA package on conda forge soon.  If that works, I'll add that as a dependency here.
2. Using OG-USA to update macros beyond wages.
3. Doing an iterated process (Tax-Calc->OG-USA->Tax-Calc->OG-USA->Tax-Calc) to ensure more consistency with macro model forecasts and the macro forecast underlying the micro data.
4.  Enabling an OG-USA specifications dictionary to be passed from the Tax-Brain entry point.

I think the above are best left to future PRs, but trust your judgement if you feel otherwise.

### CODE REVIEW

**Comment by andersonfrailey** [comment]
Thanks for working on this, @jdebacker! I agree that everything you left out can be saved for future PRs. What do you think is the best way to move forward? Should we get tests passing here and merge before the [PR #56](https://github.com/PSLmodels/Tax-Brain/pull/56) on the main branch or merge # 56 before this one?

**Comment by jdebacker** [comment]
@andersonfrailey Try syncing this branch with upstream/master.  I feel like the CI tests ought to be passing here.

**Comment by jdebacker** [comment]
The test failures suggest that the `multiprocessing` package is not in the environment. But this PR adds it to the `environment.yml` file...

**Comment by jdebacker** [comment]
> Should we get tests passing here and merge before the PR #56 on the main branch or merge # 56 before this one?

If we can, let's get tests passing here and then merge this PR, which update your branch and thus will be reflected in PR #56.  We can then merge that PR to upstream/master.

**Comment by andersonfrailey** [comment]
Sounds like a plan, @jdebacker

**Comment by jdebacker** [comment]
@andersonfrailey -- can you try to re-run the jobs on this PR?  The failures looks like a failure to setup, which is often resolved by just re-running.  Thanks!

**Comment by jdebacker** [comment]
@andersonfrailey -- actually, just merge this PR into your branch.  These CI tests will not pass on your branch as they GH action seems to only install miniconda properly on pushes to the upstream repo (I just noticed this over in the CCC repo, where the action failed on fork, but passed on the upstream).  Not sure why this is.

**Pull request merged**
